spring.application.name=spring-api-demo

# Spring JPA and Hibernate settings
spring.datasource.url=jdbc:h2:mem:test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#logging.level.org.springframework=Trace